import {
  Agent,
  AgentDashboardMetrics,
  AgentStepResult,
  AuditEntry,
  FileMatch,
  FileNode,
  GitCommitInfo,
  GitRepoStatus,
  HostProcess,
  HttpRequestResult,
  NetworkCheckResult,
  OrchestratorTask,
  PermissionRequest,
  SystemStatsResult,
  TerminalSessionInfo,
  WorkspaceInfo,
} from '../types';

declare global {
  interface Window {
    __TAURI_INTERNALS__?: any;
  }
}

const isTauri = typeof window !== 'undefined' && Boolean(window.__TAURI_INTERNALS__);

async function invokeTauri<T>(cmd: string, args?: Record<string, any>): Promise<T> {
  if (isTauri) {
    try {
      const { invoke } = await import('@tauri-apps/api/core');
      return await invoke<T>(cmd, args);
    } catch (e) {
      console.warn(`[Tauri] Command ${cmd} failed:`, e);
      throw e;
    }
  }
  return mockInvoke<T>(cmd, args);
}

// Interactive Dev/Browser fallback implementation
let mockFiles: Record<string, string> = {
  '/src/main.rs': `// Aether IDE Autonomous Kernel\nuse aether_core::EventBus;\n\nfn main() {\n    println!("AETHER Autonomous Engine Initialized");\n}`,
  '/src/agent.rs': `// Multi-Agent Collaboration Core\npub struct AgentWorker {\n    pub id: String,\n    pub role: String,\n}\n`,
  '/README.md': `# AETHER IDE\n\nNext-Generation Autonomous Multi-Agent AI IDE & Agent OS.\n`,
  '/Cargo.toml': `[package]\nname = "aether-kernel"\nversion = "0.1.0"\nedition = "2021"\n`,
};

let mockAgents: Agent[] = [
  {
    id: 'agent-arch-01',
    config: {
      name: 'Architect Prime',
      role: 'architect',
      model: 'claude-3-7-sonnet',
      temperature: 0.1,
      max_steps: 8,
      allowed_tools: ['fs_read_file', 'fs_list_dir'],
    },
    status: 'idle',
    current_task: undefined,
    steps_completed: 4,
    total_tokens_used: 1240,
  },
  {
    id: 'agent-coder-02',
    config: {
      name: 'Synthesizer Coder',
      role: 'coder',
      model: 'deepseek-r1-code',
      temperature: 0.2,
      max_steps: 12,
      allowed_tools: ['fs_read_file', 'fs_write_file', 'terminal_execute'],
    },
    status: 'idle',
    current_task: undefined,
    steps_completed: 18,
    total_tokens_used: 4890,
  },
  {
    id: 'agent-review-03',
    config: {
      name: 'Sentinel Reviewer',
      role: 'reviewer',
      model: 'gpt-4o',
      temperature: 0.1,
      max_steps: 6,
      allowed_tools: ['fs_read_file'],
    },
    status: 'idle',
    current_task: undefined,
    steps_completed: 12,
    total_tokens_used: 2150,
  },
  {
    id: 'agent-sec-04',
    config: {
      name: 'Aegis Security Auditor',
      role: 'security_auditor',
      model: 'claude-3-7-sonnet',
      temperature: 0.0,
      max_steps: 5,
      allowed_tools: ['fs_read_file'],
    },
    status: 'idle',
    current_task: undefined,
    steps_completed: 6,
    total_tokens_used: 980,
  },
];

let mockTasks: OrchestratorTask[] = [
  {
    id: 'task-101',
    title: 'Design Async Event Pipeline',
    description: 'Create zero-allocation lock-free ring buffer for agent telemetry.',
    priority: 'high',
    status: 'completed',
    depends_on: [],
    created_at: new Date(Date.now() - 3600000).toISOString(),
    completed_at: new Date(Date.now() - 1800000).toISOString(),
    result: 'Architecture approved and documented in /docs/pipeline.md',
  },
  {
    id: 'task-102',
    title: 'Implement Sandboxed PTY Session',
    description: 'Integrate native pseudo-terminal with bidirectional streaming.',
    priority: 'critical',
    status: 'completed',
    depends_on: ['task-101'],
    created_at: new Date(Date.now() - 1800000).toISOString(),
    completed_at: new Date().toISOString(),
    result: 'Terminal session active and responsive.',
  },
];

let mockAuditEntries: AuditEntry[] = [
  {
    id: 'aud-001',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    category: 'terminal_execute',
    action: 'cargo test',
    resource: 'workspace root',
    risk_level: 'safe',
    decision: 'allow_always',
    reason: 'Read-only build tool check',
  },
  {
    id: 'aud-002',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    category: 'filesystem_write',
    action: 'fs_write_file',
    resource: 'src/main.rs',
    risk_level: 'moderate',
    decision: 'allow_once',
    reason: 'Code patch generated by Coder agent',
  },
];

let mockTerminalSessions: TerminalSessionInfo[] = [
  {
    id: 'term-session-1',
    title: 'PowerShell 7',
    shell: 'pwsh.exe',
    cwd: 'd:/Rust_Proj2/AetherIDE',
  },
];

async function mockInvoke<T>(cmd: string, args?: Record<string, any>): Promise<T> {
  console.log(`[MockTauri] invoke: ${cmd}`, args);

  switch (cmd) {
    case 'get_workspace_info':
      return {
        root_path: 'd:/Rust_Proj2/AetherIDE',
        name: 'AetherIDE',
      } as unknown as T;

    case 'get_file_tree':
      return {
        name: 'AetherIDE',
        path: 'd:/Rust_Proj2/AetherIDE',
        is_dir: true,
        children: [
          {
            name: 'src',
            path: '/src',
            is_dir: true,
            children: [
              { name: 'main.rs', path: '/src/main.rs', is_dir: false, size: 210 },
              { name: 'agent.rs', path: '/src/agent.rs', is_dir: false, size: 140 },
            ],
          },
          {
            name: 'crates',
            path: '/crates',
            is_dir: true,
            children: [
              { name: 'aether-core', path: '/crates/aether-core', is_dir: true, children: [] },
              { name: 'aether-terminal', path: '/crates/aether-terminal', is_dir: true, children: [] },
              { name: 'aether-git', path: '/crates/aether-git', is_dir: true, children: [] },
            ],
          },
          { name: 'Cargo.toml', path: '/Cargo.toml', is_dir: false, size: 320 },
          { name: 'README.md', path: '/README.md', is_dir: false, size: 450 },
        ],
      } as unknown as T;

    case 'read_file': {
      const p = args?.path || '';
      return (mockFiles[p] || `// File content of ${p}\n`) as unknown as T;
    }

    case 'write_file': {
      const p = args?.path || '';
      mockFiles[p] = args?.content || '';
      return undefined as unknown as T;
    }

    case 'create_file': {
      const p = args?.path || '';
      mockFiles[p] = '';
      return undefined as unknown as T;
    }

    case 'get_git_status':
      return {
        current_branch: 'main',
        changes: [
          { path: 'crates/aether-core/src/lib.rs', status: 'modified', is_staged: true },
          { path: 'crates/aether-terminal/src/pty_session.rs', status: 'modified', is_staged: false },
          { path: 'src-tauri/src/commands.rs', status: 'added', is_staged: true },
        ],
        ahead: 1,
        behind: 0,
      } as unknown as T;

    case 'stage_file':
    case 'stage_all':
    case 'unstage_file':
      return undefined as unknown as T;

    case 'git_commit':
      return 'a4f89d1' as unknown as T;

    case 'get_git_diff':
    case 'get_file_diff':
      return `diff --git a/src/main.rs b/src/main.rs
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,4 +1,5 @@
+// Aether Autonomous Core
 fn main() {
-    println!("Old");
+    println!("New Aether Engine");
 }` as unknown as T;

    case 'list_branches':
      return ['master', 'feature/agent-os', 'develop'] as unknown as T;

    case 'checkout_branch':
    case 'create_branch':
      return undefined as unknown as T;

    case 'list_terminal_sessions':
      return mockTerminalSessions as unknown as T;

    case 'create_terminal_session': {
      const newSession: TerminalSessionInfo = {
        id: `term-${Date.now()}`,
        title: `Terminal ${mockTerminalSessions.length + 1}`,
        shell: 'pwsh.exe',
        cwd: 'd:/Rust_Proj2/AetherIDE',
      };
      mockTerminalSessions.push(newSession);
      return newSession as unknown as T;
    }

    case 'search_content': {
      const q = (args?.query || '').toLowerCase();
      const results: FileMatch[] = [];
      for (const [path, content] of Object.entries(mockFiles)) {
        const lines = content.split('\n');
        const matches = [];
        for (let i = 0; i < lines.length; i++) {
          const idx = lines[i].toLowerCase().indexOf(q);
          if (idx !== -1) {
            matches.push({
              line_number: i + 1,
              col_start: idx,
              col_end: idx + q.length,
              line_content: lines[i],
            });
          }
        }
        if (matches.length > 0) {
          results.push({ path, relative_path: path.replace(/^\//, ''), matches });
        }
      }
      return results as unknown as T;
    }

    case 'search_files': {
      const q = (args?.query || '').toLowerCase();
      const paths = Object.keys(mockFiles).filter((p) => p.toLowerCase().includes(q));
      return paths as unknown as T;
    }

    case 'list_providers':
      return [
        ['openai', 'OpenAI (GPT-4o, o3-mini)'],
        ['anthropic', 'Anthropic (Claude 3.7 Sonnet)'],
        ['ollama', 'Ollama (Local Llama 3, DeepSeek R1)'],
        ['mock', 'Mock AI Engine (Offline simulation)'],
      ] as unknown as T;

    case 'run_ai_completion': {
      const prompt = args?.prompt || '';
      return `[AETHER AI Response]\nProcessed request: "${prompt}"\nGenerated optimal solution adhering to memory rules and zero-unwraps requirement.` as unknown as T;
    }

    case 'list_agents':
      return mockAgents as unknown as T;

    case 'create_agent': {
      const newAgent: Agent = {
        id: `agent-${Date.now()}`,
        config: {
          name: args?.name || 'Custom Agent',
          role: (args?.role as any) || 'coder',
          model: args?.model || 'gpt-4o',
          temperature: 0.2,
          max_steps: 10,
          allowed_tools: ['fs_read_file', 'fs_write_file', 'terminal_execute'],
        },
        status: 'idle',
        steps_completed: 0,
        total_tokens_used: 0,
      };
      mockAgents.push(newAgent);
      return newAgent as unknown as T;
    }

    case 'run_agent_task': {
      const agentId = args?.agent_id;
      const prompt = args?.task_prompt || '';
      const targetAgent = mockAgents.find((a) => (typeof a.id === 'string' ? a.id : a.id['0']) === agentId);
      if (targetAgent) {
        targetAgent.status = 'completed';
        targetAgent.steps_completed += 2;
        targetAgent.total_tokens_used += 340;
      }
      const steps: AgentStepResult[] = [
        {
          step_index: 1,
          thought: `Analyzing goal: "${prompt}". Checking existing codebase structure...`,
          tool_name: 'fs_list_dir',
          tool_input: { path: 'src' },
          tool_output: ['main.rs', 'agent.rs'],
          is_terminal: false,
        },
        {
          step_index: 2,
          thought: `Refactoring implemented successfully. Verified with zero compiler errors.`,
          tool_name: undefined,
          tool_input: undefined,
          tool_output: undefined,
          is_terminal: true,
        },
      ];
      return steps as unknown as T;
    }

    case 'list_tasks':
      return mockTasks as unknown as T;

    case 'submit_task': {
      const newTask: OrchestratorTask = {
        id: `task-${Date.now()}`,
        title: args?.title || 'New Task',
        description: args?.description || '',
        priority: args?.priority || 'normal',
        status: 'queued',
        depends_on: [],
        created_at: new Date().toISOString(),
      };
      mockTasks.unshift(newTask);
      return (typeof newTask.id === 'string' ? newTask.id : newTask.id['0']) as unknown as T;
    }

    case 'get_dashboard_metrics': {
      return {
        running_agents: mockAgents.filter((a) => a.status === 'running').length,
        queued_tasks: mockTasks.filter((t) => t.status === 'queued').length,
        completed_tasks: mockTasks.filter((t) => t.status === 'completed').length,
        failed_tasks: 0,
        total_tokens_used: mockAgents.reduce((acc, a) => acc + a.total_tokens_used, 0),
        total_tool_calls: 42,
      } as unknown as T;
    }

    case 'run_team_pipeline': {
      const goal = args?.goal || '';
      return [
        [
          'Architect',
          [
            {
              step_index: 1,
              thought: `Architecture plan for "${goal}": decompose into 3 modules with zero circular dependencies.`,
              is_terminal: true,
            },
          ],
        ],
        [
          'Coder',
          [
            {
              step_index: 1,
              thought: `Implementing modules in Rust. Written 450 lines with async Tokio runtime.`,
              is_terminal: true,
            },
          ],
        ],
        [
          'Tester',
          [
            {
              step_index: 1,
              thought: `Ran cargo test. 18 tests passed, 0 failures.`,
              is_terminal: true,
            },
          ],
        ],
        [
          'Reviewer',
          [
            {
              step_index: 1,
              thought: `Code review: No memory leaks, clean abstractions, docs in place.`,
              is_terminal: true,
            },
          ],
        ],
        [
          'Security',
          [
            {
              step_index: 1,
              thought: `Security audit: No shell injection risks, safe file access confirmed.`,
              is_terminal: true,
            },
          ],
        ],
      ] as unknown as T;
    }

    case 'list_audit_entries':
    case 'os_get_audit_logs':
      return mockAuditEntries as unknown as T;

    case 'resolve_permission_request':
      return true as unknown as T;

    case 'os_list_processes': {
      const filter = (args?.filter || '').toLowerCase();
      const mockList: HostProcess[] = [
        { name: 'aether-desktop.exe', pid: 14208, session: 'Console', memory: '118,420 K' },
        { name: 'cargo.exe', pid: 21904, session: 'Console', memory: '84,120 K' },
        { name: 'rust-analyzer.exe', pid: 18432, session: 'Console', memory: '345,600 K' },
        { name: 'powershell.exe', pid: 9812, session: 'Console', memory: '72,110 K' },
        { name: 'node.exe', pid: 10456, session: 'Console', memory: '98,340 K' },
        { name: 'chrome.exe', pid: 3128, session: 'Console', memory: '240,180 K' },
        { name: 'git.exe', pid: 22890, session: 'Console', memory: '18,500 K' },
        { name: 'explorer.exe', pid: 4820, session: 'Console', memory: '142,300 K' },
      ];
      const filtered = filter ? mockList.filter((p) => p.name.toLowerCase().includes(filter)) : mockList;
      return { total_processes: filtered.length, processes: filtered } as unknown as T;
    }

    case 'os_kill_process': {
      const pid = args?.pid || 0;
      return {
        success: true,
        pid,
        stdout: `SUCCESS: Sent termination signal to process with PID ${pid}.`,
        stderr: '',
      } as unknown as T;
    }

    case 'os_network_check': {
      const host = args?.host || '127.0.0.1';
      const port = args?.port || 80;
      return {
        host,
        port,
        reachable: true,
        latency_ms: 12,
        status: 'connected',
      } as unknown as T;
    }

    case 'os_http_request': {
      const url = args?.url || 'https://api.github.com';
      return {
        url,
        status: 200,
        status_text: 'OK',
        headers: {
          'content-type': 'application/json; charset=utf-8',
          'x-powered-by': 'Aether-OS-Sandbox',
        },
        body: JSON.stringify(
          {
            status: 'operational',
            environment: 'host-sandboxed',
            node: 'aether-primary-v1',
            active_tunnels: 2,
            ping_ms: 14,
          },
          null,
          2
        ),
        content_length: 148,
      } as unknown as T;
    }

    case 'os_get_system_stats': {
      return {
        os: 'windows',
        arch: 'x86_64',
        family: 'windows',
        workspace: 'D:\\Rust_Proj2\\AetherIDE',
        num_cpus: 16,
      } as unknown as T;
    }

    default:
      console.warn(`[MockTauri] unhandled command: ${cmd}`);
      return null as unknown as T;
  }
}

export const TauriBridge = {
  isTauri,

  // Workspace
  getWorkspaceInfo: () => invokeTauri<WorkspaceInfo>('get_workspace_info'),
  getFileTree: (maxDepth?: number) => invokeTauri<FileNode>('get_file_tree', { maxDepth }),
  readFile: (path: string) => invokeTauri<string>('read_file', { path }),
  writeFile: (path: string, content: string) => invokeTauri<void>('write_file', { path, content }),
  createFile: (path: string) => invokeTauri<void>('create_file', { path }),
  createFolder: (path: string) => invokeTauri<void>('create_folder', { path }),
  deletePath: (path: string) => invokeTauri<void>('delete_path', { path }),
  renamePath: (oldPath: string, newPath: string) =>
    invokeTauri<void>('rename_path', { oldPath, newPath }),

  // Terminal
  createTerminalSession: (shell?: string, cols?: number, rows?: number) =>
    invokeTauri<TerminalSessionInfo>('create_terminal_session', { shell, cols, rows }),
  writeTerminalInput: (sessionId: string, data: string) =>
    invokeTauri<void>('write_terminal_input', { sessionId, data }),
  resizeTerminal: (sessionId: string, cols: number, rows: number) =>
    invokeTauri<void>('resize_terminal', { sessionId, cols, rows }),
  closeTerminalSession: (sessionId: string) =>
    invokeTauri<void>('close_terminal_session', { sessionId }),
  listTerminalSessions: () => invokeTauri<TerminalSessionInfo[]>('list_terminal_sessions'),

  // Git
  getGitStatus: () => invokeTauri<GitRepoStatus>('get_git_status'),
  stageFile: (path: string) => invokeTauri<void>('stage_file', { path }),
  stageAll: () => invokeTauri<void>('stage_all'),
  unstageFile: (path: string) => invokeTauri<void>('unstage_file', { path }),
  gitCommit: (message: string) => invokeTauri<string>('git_commit', { message }),
  getGitDiff: (staged: boolean) => invokeTauri<string>('get_git_diff', { staged }),
  getFileDiff: (path: string, staged = false) =>
    invokeTauri<string>('get_file_diff', { path, staged }),
  listBranches: () => invokeTauri<string[]>('list_branches'),
  checkoutBranch: (branchName: string) =>
    invokeTauri<void>('checkout_branch', { branchName }),
  createBranch: (branchName: string) =>
    invokeTauri<void>('create_branch', { branchName }),

  // Search
  searchContent: (query: string, isRegex = false, caseSensitive = false) =>
    invokeTauri<FileMatch[]>('search_content', { query, isRegex, caseSensitive }),
  searchFiles: (query: string, limit = 50) =>
    invokeTauri<string[]>('search_files', { query, limit }),

  // AI & Models
  listProviders: () => invokeTauri<[string, string][]>('list_providers'),
  runAiCompletion: (prompt: string, model?: string) =>
    invokeTauri<string>('run_ai_completion', { prompt, model }),

  // Agents & Orchestrator
  listAgents: () => invokeTauri<Agent[]>('list_agents'),
  createAgent: (name: string, role: string, model?: string) =>
    invokeTauri<Agent>('create_agent', { name, role, model }),
  runAgentTask: (agentId: string, taskPrompt: string) =>
    invokeTauri<AgentStepResult[]>('run_agent_task', { agentId, taskPrompt }),
  listTasks: () => invokeTauri<OrchestratorTask[]>('list_tasks'),
  submitTask: (title: string, description: string, priority = 'normal') =>
    invokeTauri<string>('submit_task', { title, description, priority }),
  getDashboardMetrics: () => invokeTauri<AgentDashboardMetrics>('get_dashboard_metrics'),
  runTeamPipeline: (goal: string) =>
    invokeTauri<[string, AgentStepResult[]][]>('run_team_pipeline', { goal }),

  // Permissions & Audit
  listAuditEntries: (count = 50) => invokeTauri<AuditEntry[]>('list_audit_entries', { count }),
  resolvePermissionRequest: (requestId: string, decision: string) =>
    invokeTauri<boolean>('resolve_permission_request', { requestId, decision }),

  // OS & Host Control
  osListProcesses: (filter?: string) =>
    invokeTauri<{ total_processes: number; processes: HostProcess[] }>('os_list_processes', { filter }),
  osKillProcess: (pid: number, force = false) =>
    invokeTauri<{ success: boolean; pid: number; stdout: string; stderr: string }>('os_kill_process', { pid, force }),
  osNetworkCheck: (host: string, port: number, timeout_ms = 3000) =>
    invokeTauri<NetworkCheckResult>('os_network_check', { host, port, timeout_ms }),
  osHttpRequest: (url: string, method = 'GET', body?: string, headers?: Record<string, string>) =>
    invokeTauri<HttpRequestResult>('os_http_request', { url, method, body, headers }),
  osGetSystemStats: () =>
    invokeTauri<SystemStatsResult>('os_get_system_stats'),
  osGetAuditLogs: (limit = 100) =>
    invokeTauri<AuditEntry[]>('os_get_audit_logs', { limit }),
};
